import React,{useState} from 'react';
import {router,useLocalSearchParams} from 'expo-router';
import {useSession} from '../../../src/session';
import {staffRoles} from '../../../src/sections.mjs';
import {Page,Label,Copy,Row,Button,Busy,ErrorText,useResource} from '../../../src/ui';
export default function Student(){const{id}=useLocalSearchParams();const{api,school}=useSession();const profile=useResource(`/v1/students/${id}`),plans=useResource(`/v1/students/${id}/plans`);const[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function create(){setBusy(true);setError('');try{const plan=await api.request(`/v1/students/${id}/plans`,{method:'POST',school:school.school.id,body:{title:`ALP - ${profile.data.name}`,sections:{studentInformation:`${profile.data.name}\nGrade ${profile.data.grade}`,strengths:profile.data.strengths,needs:profile.data.needs}}});router.push(`/plan/${plan.id}`);}catch(error){setError(error.message);}finally{setBusy(false);}}
  return <Page>{profile.loading?<Busy/>:null}<ErrorText>{error||profile.error||plans.error}</ErrorText>{profile.error||plans.error?<Button secondary onPress={()=>{profile.reload();plans.reload();}}>Retry</Button>:null}{profile.data?<><Label heading>{profile.data.name}</Label><Copy>Grade {profile.data.grade} | {profile.data.supportLevel}</Copy><Copy>{profile.data.categories.join(', ')}</Copy><Label>Strengths</Label><Copy>{profile.data.strengths||'Not recorded'}</Copy><Label>Needs</Label><Copy>{profile.data.needs||'Not recorded'}</Copy><Button secondary onPress={()=>router.push(`/messages/${id}`)}>Messages</Button><Label heading>Learning plans</Label>{plans.data?.map(plan=><Row key={plan.id} title={plan.title} detail={`${plan.status.replaceAll('_',' ')} | Revision ${plan.revision}`} onPress={()=>router.push(`/plan/${plan.id}`)}/>)}{plans.data?.length===0?<Copy>No learning plans available.</Copy>:null}{staffRoles.includes(school?.role)?<Button disabled={busy} onPress={create}>{busy?'Creating...':'Create ALP'}</Button>:null}</>:null}</Page>;
}
